# Generated by Django 5.1.3 on 2025-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='activated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
