# Generated by Django 5.1.3 on 2024-11-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='auto_app.seller'),
            preserve_default=False,
        ),
    ]
