# Generated by Django 5.1.3 on 2024-12-01 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0002_vehicle_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='number_of_models',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='make',
            name='number_of_vehicles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='number_of_vehicles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency', to='auto_app.currency'),
        ),
    ]
