# Generated by Django 5.1.3 on 2024-12-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0003_make_number_of_models_make_number_of_vehicles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='car_class',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='model',
            name='drivetrain',
            field=models.CharField(choices=[('front_wheel_drive', 'Front Wheel Drive'), ('rear_wheel_drive', 'Rear Wheel Drive'), ('all_wheel_drive', 'All Wheel Drive')], default='front_wheel_drive', max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='model',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
