# Generated by Django 5.1.3 on 2024-12-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0004_model_car_class_model_drivetrain_model_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
