# Generated by Django 5.1.3 on 2024-12-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0008_seller_user_alter_vehicle_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.ImageField(null=True, upload_to='seller_photos/'),
        ),
    ]
