# Generated by Django 5.1.3 on 2025-01-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0013_savedlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
    ]
