# Generated by Django 5.1.3 on 2025-01-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0014_remove_seller_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_city', to='auto_app.city'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='auto_app.city'),
        ),
    ]
