# Generated by Django 5.1.3 on 2025-10-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0017_vehiclephoto_cdn_photo_vehiclephoto_cdn_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
