# Generated by Django 5.1.3 on 2025-10-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0018_remove_seller_zip_code_alter_seller_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
