# Generated by Django 5.1.3 on 2025-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0019_vehicle_chassis_number_vehicle_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
