# Generated by Django 5.1.3 on 2025-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0020_vehicle_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_dealer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
