# Generated by Django 5.1.3 on 2025-11-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0023_city_created_at_city_created_by_city_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclephoto',
            name='height',
            field=models.PositiveIntegerField(default=96),
        ),
        migrations.AddField(
            model_name='vehiclephoto',
            name='width',
            field=models.PositiveIntegerField(default=128),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='temporary',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehiclephoto',
            name='is_main',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehiclephoto',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='auto_app.vehicle'),
        ),
    ]
