# Generated by Django 5.1.3 on 2025-11-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0024_vehiclephoto_height_vehiclephoto_width_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account (Deprecated)', 'verbose_name_plural': 'Accounts (Deprecated)'},
        ),
        migrations.AddField(
            model_name='seller',
            name='is_cms_user',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='auto_app.role'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_city', to='auto_app.city'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='country',
            field=models.CharField(blank=True, default='ZW', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_photos/'),
        ),
    ]
